version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./src/main/resources/initdb/init-tables.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - "5432:5432"