create table writer (
    id int primary key generated by default as identity not null,
    full_name varchar (256) not null
);

create table book (
    id int primary key generated by default as identity,
    title varchar (128),
    writer_id int references writer (id) not null
);

create table comment (
    id int primary key generated by default as identity,
    author varchar (64) not null,
    comment varchar (256) not null,
    book_id int references book (id) not null
);

-- with autoincrement and without autoincrement
insert into writer (full_name) values ('Bob Claers');
insert into writer (full_name) values ('Nikita Moae');
insert into writer (id, full_name) values (3, 'A. S. Pushkin');

-- without autoincrement only
insert into book (id, title, writer_id) values (1, 'How to cook', 1);
insert into book (id, title, writer_id) values (2, 'How to sleep', 1);
insert into book (id, title, writer_id) values (3, 'Why "How to cook" is bull shit', 2);
insert into book (id, title, writer_id) values (4, 'Daughter of the Captain', 3);

-- with autoincrement only
insert into comment (author, comment, book_id) values ('Bob Claers', 'No! Your book is bull shit!', 3);
insert into comment (author, comment, book_id) values ('Bob Marley', 'Beautiful!!!', 4);